# Generated by Django 6.0.4 on 2026-05-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_recruiterprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='recruiterprofile',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='recruiterprofile',
            name='industry',
            field=models.CharField(blank=True, choices=[('Technology', 'Technology'), ('Finance', 'Finance'), ('Healthcare', 'Healthcare'), ('E-Commerce', 'E-Commerce'), ('Manufacturing', 'Manufacturing'), ('Consulting', 'Consulting'), ('Education', 'Education'), ('Media', 'Media'), ('Telecom', 'Telecom'), ('Other', 'Other')], max_length=50),
        ),
    ]
