# Generated by Django 6.0.4 on 2026-05-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_remove_recruiterprofile_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiterprofile',
            name='admin_remark',
            field=models.TextField(blank=True, help_text="Admin's reason for approval/rejection"),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='verification_note',
            field=models.TextField(blank=True, help_text="Recruiter's message to admin"),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='verification_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='verification_status',
            field=models.CharField(choices=[('not_requested', 'Not Requested'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='recruiterprofile',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
