# Generated by Django 6.0.4 on 2026-05-09 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0003_application_resume'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='placementdrive',
            name='package',
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='company_logo',
            field=models.ImageField(blank=True, help_text='Upload company logo', null=True, upload_to='company_logos/'),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='salary_amount',
            field=models.FloatField(blank=True, help_text='Enter the numeric value (e.g., 12.5)', null=True),
        ),
        migrations.AddField(
            model_name='placementdrive',
            name='salary_type',
            field=models.CharField(choices=[('ctc', 'CTC (Cost to Company)'), ('lpa', 'LPA (Lakhs Per Annum)'), ('stipend', 'Stipend (Per Month)')], default='lpa', max_length=10),
        ),
    ]
