# Generated by Django 6.0.4 on 2026-05-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0004_remove_placementdrive_package_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placementdrive',
            name='salary_type',
            field=models.CharField(choices=[('ctc', 'CTC (Cost to Company)'), ('lpa', 'LPA (Lakhs Per Annum)'), ('stipend', 'Stipend (Per Month)'), ('not_disclosed', 'Not Disclosed')], default='lpa', max_length=20),
        ),
    ]
