# Generated by Django 6.0.4 on 2026-05-10 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('placements', '0006_bookmark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_chat_unlocked_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='placements.application')),
                ('drive', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='placements.placementdrive')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_conversations', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('student', 'recruiter', 'drive')},
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('student', 'Student'), ('recruiter', 'Recruiter'), ('system', 'System')], max_length=10)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('template', 'Template'), ('file', 'File Upload'), ('system', 'System Alert')], default='text', max_length=10)),
                ('content', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='chat_files/')),
                ('file_category', models.CharField(blank=True, max_length=50)),
                ('template_action', models.CharField(blank=True, max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='placements.conversation')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
